apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: openclaw
data:
  openclaw.json: |
    {
      "browser": {
        "enabled": true,
        "headless": true,
        "noSandbox": true,
        "executablePath": "/usr/bin/brave-browser"
      },
      "agents": {
        "defaults": {
          "workspace": "/home/node/.openclaw/workspace",
          "model": {
            "primary": "google/gemini-2.5-flash",
            "fallbacks": ["google/gemini-2.5-flash-lite", "google/gemini-2.0-flash", "google/gemini-2.0-flash-lite"]
          },
          "bootstrapMaxChars": 5000
        },
        "list": [
          {
            "id": "main",
            "identity": {
              "name": "Clawd",
              "theme": "helpful assistant",
              "emoji": "ðŸ¦ž"
            }
          }
        ]
      },
      "auth": {
        "profiles": {
          "gemini:api": {
            "provider": "google",
            "mode": "api_key"
          }
        },
        "order": {
          "google": ["gemini:api"]
        }
      },
      "channels": {
        "telegram": {
          "enabled": true,
          "botToken": "${TELEGRAM_BOT_TOKEN}",
          "dmPolicy": "pairing",
          "allowFrom": ["803653603", "401006345", "363003388"]
        }
      },
      "messages": {
        "responsePrefix": "ðŸ¤“"
      },
      "plugins": {
        "entries": {
          "telegram": {
            "enabled": true
          }
        }
      },
      "gateway": {
        "mode": "local",
        "bind": "lan",
        "port": 18789,
        "auth": {
          "mode": "token",
          "token": "${OPENCLAW_GATEWAY_TOKEN}"
        }
      }
    }
